# Generated by Django 3.0.5 on 2020-04-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200427_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=models.SlugField(default='fdd', max_length=250),
            preserve_default=False,
        ),
    ]
