# Generated by Django 3.0.5 on 2020-04-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='house_number',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='street',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Улица'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]
