# Generated by Django 3.0.5 on 2020-04-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0003_auto_20200421_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.AddField(
            model_name='clinic',
            name='service',
            field=models.ManyToManyField(to='clinics.ClinicService'),
        ),
    ]
