# Generated by Django 3.0.5 on 2020-04-25 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('clinics', '0005_auto_20200421_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinic',
            name='city',
        ),
        migrations.AddField(
            model_name='clinic',
            name='city',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='locations.City'),
            preserve_default=False,
        ),
    ]
