# Generated by Django 3.0.5 on 2020-04-29 13:29

import clinics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0006_auto_20200425_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clinics.models.image_path, verbose_name='Фото'),
        ),
    ]
