# Generated by Django 3.0.5 on 2020-04-21 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import doctors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('price', models.FloatField(default=0, verbose_name='Стоимость консультации')),
                ('experience', models.CharField(max_length=300, verbose_name='Стаж')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Врач',
                'verbose_name_plural': 'Врачи',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Квалификационная категория',
                'verbose_name_plural': 'Квалификационные категории',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=250)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Годы работы')),
                ('description', models.TextField(blank=True, verbose_name='Место работы')),
                ('position', models.PositiveIntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_work', to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Место работы',
                'verbose_name_plural': 'Место работы',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=100, null=True, verbose_name='Годы обучения')),
                ('description', models.TextField(blank=True, verbose_name='Вуз и специальность')),
                ('position', models.PositiveIntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_education', to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образование',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.Rank'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.ManyToManyField(to='doctors.Service'),
        ),
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=doctors.models.image_path)),
                ('position', models.PositiveIntegerField(default=1)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_diplom', to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
                'ordering': ('position',),
            },
        ),
    ]
